apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pr-brancher-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pr-brancher
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: pr-brancher-role
  apiGroup: rbac.authorization.k8s.io
